name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Thanks for contributing for the first time! It's very appreciated, and it helps me solve my errors! Thank you for reporting this bug. I will fix it as soon as I see your issue."
        pr-message: "Thanks for contributing for the first time! It's very appreciated, and it helps me make this project better for other users! Thanks for the pull request."
